spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
  application:
    name: payment-service
eureka:
  instance:
    instance-id: payment-service:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
server:
  port: ${SERVER_PORT:8082}
ticketly:
  observability:
    enabled: true
    slow-call-threshold-ms: 500