spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketly
    username: ticketly
    password: ticketly
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight-sql: true
  liquibase:
    contexts: dev
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE