spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
  cache:
    type: redis
  cloud:
    openfeign:
      client:
        config:
          payment-service:
            url: ${PAYMENT_SERVICE_URL:http://localhost:8082}
            connect-timeout: 2000
            read-timeout: 5000
            logger-level: full
ticketly:
  max-seats-per-reservation: ${MAX_SEATS_PER_RESERVATION:10}
  seat-hold-minutes: ${SEAT_HOLD_MINUTES:15}
  service-fee-percent: ${SERVICE_FEE_PERCENT:0.1}
  hold-cleanup-cron: ${HOLD_CLEANUP_CRON:0 * * * * *}
  finish-events-cron: ${FINISH_EVENTS_CRON:0 0 * * * *}
eureka:
  instance:
    instance-id: ticketing-service:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}