spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
ticketly:
  max-seats-per-reservation: 10
  seat-hold-minutes: 15
  service-fee-percent: 0.1
  hold-cleanup-cron: '0 * * * * *'